"""
GAÏRUS PROVIDER CATALOG
Catalogue extensible de fournisseurs IA.
Les statuts tarifaires sont indicatifs et doivent être revérifiés avant activation.
"""

PROVIDERS = [
    # API cloud
    {
        "id": "gemini",
        "name": "Google Gemini",
        "env": "GEMINI_API_KEY",
        "model_env": "GEMINI_MODEL",
        "default_model": "gemini-3.6-flash",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "vision"],
        "pricing": "free_tier",
        "priority": 10,
    },
    {
        "id": "groq",
        "name": "Groq",
        "env": "GROQ_API_KEY",
        "model_env": "GROQ_MODEL",
        "default_model": "openai/gpt-oss-120b",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "free_tier",
        "priority": 15,
    },
    {
        "id": "kimi",
        "name": "Kimi / Moonshot",
        "env": "KIMI_API_KEY",
        "model_env": "KIMI_MODEL",
        "default_model": "kimi-k3",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "account_dependent",
        "priority": 20,
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "env": "OPENROUTER_API_KEY",
        "model_env": "OPENROUTER_MODEL",
        "default_model": "openrouter/free",
        "type": "gateway",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code", "vision"],
        "pricing": "free_models",
        "priority": 30,
    },
    {
        "id": "mistral",
        "name": "Mistral AI",
        "env": "MISTRAL_API_KEY",
        "model_env": "MISTRAL_MODEL",
        "default_model": "mistral-small-latest",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "free_tier",
        "priority": 35,
    },
    {
        "id": "huggingface",
        "name": "Hugging Face",
        "env": "HF_TOKEN",
        "model_env": "HF_MODEL",
        "default_model": "Qwen/Qwen3-32B",
        "type": "gateway",
        "protocol": "huggingface",
        "capabilities": ["text", "code", "vision"],
        "pricing": "free_tier",
        "priority": 40,
    },
    {
        "id": "cloudflare",
        "name": "Cloudflare Workers AI",
        "env": "CLOUDFLARE_API_TOKEN",
        "model_env": "CLOUDFLARE_MODEL",
        "default_model": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
        "type": "cloud",
        "protocol": "cloudflare",
        "capabilities": ["text", "code"],
        "pricing": "free_tier",
        "priority": 45,
    },
    {
        "id": "cohere",
        "name": "Cohere",
        "env": "COHERE_API_KEY",
        "model_env": "COHERE_MODEL",
        "default_model": "command-a-03-2025",
        "type": "cloud",
        "protocol": "cohere",
        "capabilities": ["text", "reasoning"],
        "pricing": "free_tier",
        "priority": 50,
    },
    {
        "id": "zai",
        "name": "Z.ai / Zhipu",
        "env": "ZAI_API_KEY",
        "model_env": "ZAI_MODEL",
        "default_model": "GLM-4.7-Flash",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "free_tier",
        "priority": 55,
    },
    {
        "id": "nvidia",
        "name": "NVIDIA NIM",
        "env": "NVIDIA_API_KEY",
        "model_env": "NVIDIA_MODEL",
        "default_model": "nvidia/llama-3.3-nemotron-super-49b-v1",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning"],
        "pricing": "free_or_trial",
        "priority": 60,
    },
    {
        "id": "chutes",
        "name": "Chutes",
        "env": "CHUTES_API_KEY",
        "model_env": "CHUTES_MODEL",
        "default_model": "deepseek-ai/DeepSeek-R1",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "free_or_account_dependent",
        "priority": 65,
    },
    {
        "id": "siliconflow",
        "name": "SiliconFlow",
        "env": "SILICONFLOW_API_KEY",
        "model_env": "SILICONFLOW_MODEL",
        "default_model": "Qwen/Qwen3-32B",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "free_or_account_dependent",
        "priority": 70,
    },
    {
        "id": "ovh",
        "name": "OVHcloud AI Endpoints",
        "env": "OVH_API_KEY",
        "model_env": "OVH_MODEL",
        "default_model": "Qwen3-Coder-30B-A3B-Instruct",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "account_dependent",
        "priority": 75,
    },
    {
        "id": "fireworks",
        "name": "Fireworks AI",
        "env": "FIREWORKS_API_KEY",
        "model_env": "FIREWORKS_MODEL",
        "default_model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "trial_or_account_dependent",
        "priority": 80,
    },
    {
        "id": "together",
        "name": "Together AI",
        "env": "TOGETHER_API_KEY",
        "model_env": "TOGETHER_MODEL",
        "default_model": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "trial_or_account_dependent",
        "priority": 85,
    },
    {
        "id": "cerebras",
        "name": "Cerebras",
        "env": "CEREBRAS_API_KEY",
        "model_env": "CEREBRAS_MODEL",
        "default_model": "llama-3.3-70b",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "account_dependent",
        "priority": 90,
    },
    {
        "id": "ai21",
        "name": "AI21",
        "env": "AI21_API_KEY",
        "model_env": "AI21_MODEL",
        "default_model": "jamba-mini",
        "type": "cloud",
        "protocol": "ai21",
        "capabilities": ["text"],
        "pricing": "trial_or_account_dependent",
        "priority": 95,
    },
    {
        "id": "deepinfra",
        "name": "DeepInfra",
        "env": "DEEPINFRA_API_KEY",
        "model_env": "DEEPINFRA_MODEL",
        "default_model": "meta-llama/Llama-3.3-70B-Instruct",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "trial_or_account_dependent",
        "priority": 100,
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "env": "DEEPSEEK_API_KEY",
        "model_env": "DEEPSEEK_MODEL",
        "default_model": "deepseek-chat",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "reasoning", "code"],
        "pricing": "account_dependent",
        "priority": 105,
    },
    {
        "id": "perplexity",
        "name": "Perplexity",
        "env": "PERPLEXITY_API_KEY",
        "model_env": "PERPLEXITY_MODEL",
        "default_model": "sonar",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "web"],
        "pricing": "trial_or_account_dependent",
        "priority": 110,
    },
    {
        "id": "sambanova",
        "name": "SambaNova",
        "env": "SAMBANOVA_API_KEY",
        "model_env": "SAMBANOVA_MODEL",
        "default_model": "Meta-Llama-3.3-70B-Instruct",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "account_dependent",
        "priority": 115,
    },
    {
        "id": "lepton",
        "name": "Lepton AI",
        "env": "LEPTON_API_KEY",
        "model_env": "LEPTON_MODEL",
        "default_model": "llama3.1-70b",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "account_dependent",
        "priority": 120,
    },
    {
        "id": "novita",
        "name": "Novita AI",
        "env": "NOVITA_API_KEY",
        "model_env": "NOVITA_MODEL",
        "default_model": "deepseek/deepseek-v3",
        "type": "cloud",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "trial_or_account_dependent",
        "priority": 125,
    },

    # Moteurs locaux, sans API distante
    {
        "id": "ollama",
        "name": "Ollama",
        "env": "OLLAMA_BASE_URL",
        "model_env": "OLLAMA_MODEL",
        "default_model": "llama3.2",
        "type": "local",
        "protocol": "ollama",
        "capabilities": ["text", "code", "reasoning"],
        "pricing": "local",
        "priority": 200,
    },
    {
        "id": "lmstudio",
        "name": "LM Studio",
        "env": "LMSTUDIO_BASE_URL",
        "model_env": "LMSTUDIO_MODEL",
        "default_model": "local-model",
        "type": "local",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "local",
        "priority": 210,
    },
    {
        "id": "llamacpp",
        "name": "llama.cpp",
        "env": "LLAMACPP_BASE_URL",
        "model_env": "LLAMACPP_MODEL",
        "default_model": "local-model",
        "type": "local",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "local",
        "priority": 220,
    },
    {
        "id": "vllm",
        "name": "vLLM",
        "env": "VLLM_BASE_URL",
        "model_env": "VLLM_MODEL",
        "default_model": "local-model",
        "type": "local",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code", "reasoning"],
        "pricing": "local",
        "priority": 230,
    },
    {
        "id": "koboldcpp",
        "name": "KoboldCpp",
        "env": "KOBOLDCPP_BASE_URL",
        "model_env": "KOBOLDCPP_MODEL",
        "default_model": "local-model",
        "type": "local",
        "protocol": "openai-compatible",
        "capabilities": ["text"],
        "pricing": "local",
        "priority": 240,
    },
    {
        "id": "jan",
        "name": "Jan",
        "env": "JAN_BASE_URL",
        "model_env": "JAN_MODEL",
        "default_model": "local-model",
        "type": "local",
        "protocol": "openai-compatible",
        "capabilities": ["text", "code"],
        "pricing": "local",
        "priority": 250,
    },
]


def get_provider(provider_id):
    for p in PROVIDERS:
        if p["id"] == provider_id:
            return p
    return None


def configured_providers(environ):
    result = []
    for p in PROVIDERS:
        if p["type"] == "local":
            base = environ.get(p["env"])
            if base:
                result.append(p)
        elif environ.get(p["env"]):
            result.append(p)
    return sorted(result, key=lambda x: x["priority"])


def catalog_summary():
    return {
        "total": len(PROVIDERS),
        "cloud": len([p for p in PROVIDERS if p["type"] == "cloud"]),
        "gateway": len([p for p in PROVIDERS if p["type"] == "gateway"]),
        "local": len([p for p in PROVIDERS if p["type"] == "local"]),
    }
